image: hosttoday/ht-docker-node:npmts

stages:
- test1
- test2
- test3
- release

testLEGACY:
  stage: test1
  script:
    - npmci test legacy
  tags:
    - docker

testLTS:
  stage: test2
  script:
    - npmci test lts
  tags:
    - docker
    
testSTABLE:
  stage: test3
  script:
    - npmci test stable
  tags:
    - docker

release:
  stage: release
  script:
    - npmci publish
  only:
    - tags
  tags:
    - docker